apiVersion: v1
data:
  mapRoles: |
    - groups:
      - system:bootstrappers
      - system:nodes
      rolearn: arn:aws:iam::862847718550:role/eksctl-simple-jwt-api-nodegroup-n-NodeInstanceRole-E6GMEMYW5SEU
      username: system:node:{{EC2PrivateDNSName}}
    - groups:
      - system:masters
      rolearn: arn:aws:iam::862847718550:role/UdacityFlaskDeployCBKubectlRole
      username: build
  mapUsers: |
    []
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-15T01:21:20Z"
  name: aws-auth
  namespace: kube-system
  resourceVersion: "55487"
  selfLink: /api/v1/namespaces/kube-system/configmaps/aws-auth
  uid: fa19839f-0fd5-411c-b6c6-e3f4ba90f7b3
